--Sequences Initial
CREATE SEQUENCE BadaniaOkresoweSeq;
CREATE SEQUENCE CzescEksploatacyjnaSeq;
CREATE SEQUENCE CzescSamochodowaSeq;
CREATE SEQUENCE DaneKontaktoweSeq;
CREATE SEQUENCE DyrektorSeq;
CREATE SEQUENCE HistoriaNaprawySeq;
CREATE SEQUENCE KierownikSeq;
CREATE SEQUENCE KlientIndywidualnySeq;
CREATE SEQUENCE KlientInstytucjonalnySeq;
CREATE SEQUENCE NaprawaSeq;
CREATE SEQUENCE PlacowkaSeq;
CREATE SEQUENCE PracownikSzeregowySeq;
CREATE SEQUENCE PrzygotowanieDoSezonuSeq;
CREATE SEQUENCE RaportSeq;
CREATE SEQUENCE RezerwacjaSeq;
CREATE SEQUENCE RodzajCzesciEksploatacyjnejSeq;
CREATE SEQUENCE RodzajCzesciSamochodowejSeq;
CREATE SEQUENCE SamochodSeq;
CREATE SEQUENCE SerwisSeq;
CREATE SEQUENCE SerwisMagazynSeq;
CREATE SEQUENCE SkierowanieNaBadanieSeq;
CREATE SEQUENCE WypozyczalniaSeq;
CREATE SEQUENCE WypozyczenieSeq;
CREATE SEQUENCE ZamowienieWewnetrznySeq;
CREATE SEQUENCE ZamowienieZewnetrzneSeq;
CREATE SEQUENCE ZewnetrznyDostawcaSeq;
CREATE SEQUENCE ZgloszenieSeq;
CREATE SEQUENCE ZgloszenieZewnetrzneSeq;

-- object: public."KLIENT" | type: TABLE --
-- DROP TABLE IF EXISTS public."KLIENT" CASCADE;
CREATE TABLE public."KLIENT"(
	id integer NOT NULL,
	login varchar(20) NOT NULL,
	haslo varchar(20) NOT NULL,
	"id_DANE KONTAKTOWE" integer NOT NULL,
	CONSTRAINT "KLIENT_ID" PRIMARY KEY (id)

);
-- ddl-end --
ALTER TABLE public."KLIENT" OWNER TO postgres;
-- ddl-end --

-- object: public."KLIENT INDYWIDUALNY" | type: TABLE --
-- DROP TABLE IF EXISTS public."KLIENT INDYWIDUALNY" CASCADE;
CREATE TABLE public."KLIENT INDYWIDUALNY"(
	id integer NOT NULL DEFAULT nextval('KlientIndywidualnySeq'),
	imie varchar(20) NOT NULL,
	nazwisko varchar(30) NOT NULL,
	CONSTRAINT "KLIENT_INDYWIDUALNY_PK" PRIMARY KEY (id)

) INHERITS(public."KLIENT")
;
-- ddl-end --
ALTER TABLE public."KLIENT INDYWIDUALNY" OWNER TO postgres;
-- ddl-end --

-- object: public."KLIENT INSTYTUCJONALNY" | type: TABLE --
-- DROP TABLE IF EXISTS public."KLIENT INSTYTUCJONALNY" CASCADE;
CREATE TABLE public."KLIENT INSTYTUCJONALNY"(
	id integer NOT NULL DEFAULT nextval('KlientInstytucjonalnySeq'),
	"NIP" varchar(10) NOT NULL,
	"REGON" varchar(14) NOT NULL,
	"id_PRACOWNIK SZEREGOWY" integer NOT NULL,
	CONSTRAINT id PRIMARY KEY (id)

) INHERITS(public."KLIENT")
;
-- ddl-end --
ALTER TABLE public."KLIENT INSTYTUCJONALNY" OWNER TO postgres;
-- ddl-end --

-- object: public."DANE KONTAKTOWE" | type: TABLE --
-- DROP TABLE IF EXISTS public."DANE KONTAKTOWE" CASCADE;
CREATE TABLE public."DANE KONTAKTOWE"(
	id integer NOT NULL DEFAULT nextval('DaneKontaktoweSeq'),
	ulica varchar(80) NOT NULL,
	"numer domu" integer NOT NULL,
	"numer lokalu" integer,
	telefon varchar(15) NOT NULL,
	miasto varchar(30) NOT NULL,
	CONSTRAINT "DANE_KONTAKTOWE_ID" PRIMARY KEY (id)

);
-- ddl-end --
ALTER TABLE public."DANE KONTAKTOWE" OWNER TO postgres;
-- ddl-end --

-- object: public."PRACOWNIK" | type: TABLE --
-- DROP TABLE IF EXISTS public."PRACOWNIK" CASCADE;
CREATE TABLE public."PRACOWNIK"(
	id integer NOT NULL,
	imie varchar(20) NOT NULL,
	nazwisko varchar(30) NOT NULL,
	"PESEL" varchar(11),
	"id_DANE KONTAKTOWE" integer NOT NULL,
	"id_PLACOWKA" integer NOT NULL,
	login varchar(20) NOT NULL,
	haslo varchar(20) NOT NULL,
	data_zmiany_hasla timestamp NOT NULL,
	CONSTRAINT "PRACOWNIK_ID" PRIMARY KEY (id)

);
-- ddl-end --
ALTER TABLE public."PRACOWNIK" OWNER TO postgres;
-- ddl-end --

-- object: public.rodzaj_dzialu | type: TYPE --
-- DROP TYPE IF EXISTS public.rodzaj_dzialu CASCADE;
CREATE TYPE public.rodzaj_dzialu AS
 ENUM ('SERWIS','SERWIS MAGAZYN','WYPOZYCZALNIA');
-- ddl-end --
ALTER TYPE public.rodzaj_dzialu OWNER TO postgres;
-- ddl-end --

-- object: public."KIEROWNIK" | type: TABLE --
-- DROP TABLE IF EXISTS public."KIEROWNIK" CASCADE;
CREATE TABLE public."KIEROWNIK"(
	id integer NOT NULL DEFAULT nextval('KierownikSeq'),
	"id_DYREKTOR" integer NOT NULL,
	dzial public.rodzaj_dzialu NOT NULL,
	CONSTRAINT "KIEROWNIK_ID" PRIMARY KEY (id)

) INHERITS(public."PRACOWNIK")
;
-- ddl-end --
ALTER TABLE public."KIEROWNIK" OWNER TO postgres;
-- ddl-end --

-- object: public."DYREKTOR" | type: TABLE --
-- DROP TABLE IF EXISTS public."DYREKTOR" CASCADE;
CREATE TABLE public."DYREKTOR"(
	id integer NOT NULL DEFAULT nextval('DyrektorSeq'),
	CONSTRAINT "DYREKTOR_ID" PRIMARY KEY (id)

) INHERITS(public."PRACOWNIK")
;
-- ddl-end --
ALTER TABLE public."DYREKTOR" OWNER TO postgres;
-- ddl-end --

-- object: public."PRACOWNIK SZEREGOWY" | type: TABLE --
-- DROP TABLE IF EXISTS public."PRACOWNIK SZEREGOWY" CASCADE;
CREATE TABLE public."PRACOWNIK SZEREGOWY"(
	id integer NOT NULL DEFAULT nextval('PracownikSzeregowySeq'),
	dzial public.rodzaj_dzialu NOT NULL,
	"id_KIEROWNIK" integer NOT NULL,
	CONSTRAINT "PRACOWNIK_SZEREGOWY_ID" PRIMARY KEY (id)

) INHERITS(public."PRACOWNIK")
;
-- ddl-end --
ALTER TABLE public."PRACOWNIK SZEREGOWY" OWNER TO postgres;
-- ddl-end --

-- object: "DANE KONTAKTOWE_fk" | type: CONSTRAINT --
-- ALTER TABLE public."PRACOWNIK" DROP CONSTRAINT IF EXISTS "DANE KONTAKTOWE_fk" CASCADE;
ALTER TABLE public."PRACOWNIK" ADD CONSTRAINT "DANE KONTAKTOWE_fk" FOREIGN KEY ("id_DANE KONTAKTOWE")
REFERENCES public."DANE KONTAKTOWE" (id) MATCH FULL
ON DELETE RESTRICT ON UPDATE CASCADE;
-- ddl-end --

-- object: "PRACOWNIK_uq" | type: CONSTRAINT --
-- ALTER TABLE public."PRACOWNIK" DROP CONSTRAINT IF EXISTS "PRACOWNIK_uq" CASCADE;
ALTER TABLE public."PRACOWNIK" ADD CONSTRAINT "PRACOWNIK_uq" UNIQUE ("id_DANE KONTAKTOWE");
-- ddl-end --

-- object: public."PLACOWKA" | type: TABLE --
-- DROP TABLE IF EXISTS public."PLACOWKA" CASCADE;
CREATE TABLE public."PLACOWKA"(
	id integer NOT NULL DEFAULT nextval('PlacowkaSeq'),
	"id_DANE KONTAKTOWE" integer NOT NULL,
	CONSTRAINT "PLACOWKA_ID" PRIMARY KEY (id)

);
-- ddl-end --
ALTER TABLE public."PLACOWKA" OWNER TO postgres;
-- ddl-end --

-- object: "PLACOWKA_fk" | type: CONSTRAINT --
-- ALTER TABLE public."PRACOWNIK" DROP CONSTRAINT IF EXISTS "PLACOWKA_fk" CASCADE;
ALTER TABLE public."PRACOWNIK" ADD CONSTRAINT "PLACOWKA_fk" FOREIGN KEY ("id_PLACOWKA")
REFERENCES public."PLACOWKA" (id) MATCH FULL
ON DELETE RESTRICT ON UPDATE CASCADE;
-- ddl-end --

-- object: "KIEROWNIK_fk" | type: CONSTRAINT --
-- ALTER TABLE public."PRACOWNIK SZEREGOWY" DROP CONSTRAINT IF EXISTS "KIEROWNIK_fk" CASCADE;
ALTER TABLE public."PRACOWNIK SZEREGOWY" ADD CONSTRAINT "KIEROWNIK_fk" FOREIGN KEY ("id_KIEROWNIK")
REFERENCES public."KIEROWNIK" (id) MATCH FULL
ON DELETE RESTRICT ON UPDATE CASCADE;
-- ddl-end --

-- object: "DYREKTOR_fk" | type: CONSTRAINT --
-- ALTER TABLE public."KIEROWNIK" DROP CONSTRAINT IF EXISTS "DYREKTOR_fk" CASCADE;
ALTER TABLE public."KIEROWNIK" ADD CONSTRAINT "DYREKTOR_fk" FOREIGN KEY ("id_DYREKTOR")
REFERENCES public."DYREKTOR" (id) MATCH FULL
ON DELETE RESTRICT ON UPDATE CASCADE;
-- ddl-end --

-- object: public."SERWIS MAGAZYN" | type: TABLE --
-- DROP TABLE IF EXISTS public."SERWIS MAGAZYN" CASCADE;
CREATE TABLE public."SERWIS MAGAZYN"(
	id integer NOT NULL DEFAULT nextval('SerwisMagazynSeq'),
	"id_PLACOWKA" integer NOT NULL,
	CONSTRAINT "SERWIS_MAGAZYN_ID" PRIMARY KEY (id)

);
-- ddl-end --
ALTER TABLE public."SERWIS MAGAZYN" OWNER TO postgres;
-- ddl-end --

-- object: public."SERWIS" | type: TABLE --
-- DROP TABLE IF EXISTS public."SERWIS" CASCADE;
CREATE TABLE public."SERWIS"(
	id integer NOT NULL DEFAULT nextval('SerwisSeq'),
	"id_PLACOWKA" integer NOT NULL,
	CONSTRAINT "SERWIS_ID" PRIMARY KEY (id)

);
-- ddl-end --
ALTER TABLE public."SERWIS" OWNER TO postgres;
-- ddl-end --

-- object: public."WYPOZYCZALNIA" | type: TABLE --
-- DROP TABLE IF EXISTS public."WYPOZYCZALNIA" CASCADE;
CREATE TABLE public."WYPOZYCZALNIA"(
	id integer NOT NULL DEFAULT nextval('WypozyczalniaSeq'),
	"id_PLACOWKA" integer NOT NULL,
	CONSTRAINT "WYPOZYCZALNIA_ID" PRIMARY KEY (id)

);
-- ddl-end --
ALTER TABLE public."WYPOZYCZALNIA" OWNER TO postgres;
-- ddl-end --

-- object: "PLACOWKA_fk" | type: CONSTRAINT --
-- ALTER TABLE public."SERWIS MAGAZYN" DROP CONSTRAINT IF EXISTS "PLACOWKA_fk" CASCADE;
ALTER TABLE public."SERWIS MAGAZYN" ADD CONSTRAINT "PLACOWKA_fk" FOREIGN KEY ("id_PLACOWKA")
REFERENCES public."PLACOWKA" (id) MATCH FULL
ON DELETE RESTRICT ON UPDATE CASCADE;
-- ddl-end --

-- object: "SERWIS MAGAZYN_uq" | type: CONSTRAINT --
-- ALTER TABLE public."SERWIS MAGAZYN" DROP CONSTRAINT IF EXISTS "SERWIS MAGAZYN_uq" CASCADE;
ALTER TABLE public."SERWIS MAGAZYN" ADD CONSTRAINT "SERWIS MAGAZYN_uq" UNIQUE ("id_PLACOWKA");
-- ddl-end --

-- object: "PLACOWKA_fk" | type: CONSTRAINT --
-- ALTER TABLE public."SERWIS" DROP CONSTRAINT IF EXISTS "PLACOWKA_fk" CASCADE;
ALTER TABLE public."SERWIS" ADD CONSTRAINT "PLACOWKA_fk" FOREIGN KEY ("id_PLACOWKA")
REFERENCES public."PLACOWKA" (id) MATCH FULL
ON DELETE RESTRICT ON UPDATE CASCADE;
-- ddl-end --

-- object: "SERWIS_uq" | type: CONSTRAINT --
-- ALTER TABLE public."SERWIS" DROP CONSTRAINT IF EXISTS "SERWIS_uq" CASCADE;
ALTER TABLE public."SERWIS" ADD CONSTRAINT "SERWIS_uq" UNIQUE ("id_PLACOWKA");
-- ddl-end --

-- object: "DANE KONTAKTOWE_fk" | type: CONSTRAINT --
-- ALTER TABLE public."KLIENT" DROP CONSTRAINT IF EXISTS "DANE KONTAKTOWE_fk" CASCADE;
ALTER TABLE public."KLIENT" ADD CONSTRAINT "DANE KONTAKTOWE_fk" FOREIGN KEY ("id_DANE KONTAKTOWE")
REFERENCES public."DANE KONTAKTOWE" (id) MATCH FULL
ON DELETE RESTRICT ON UPDATE CASCADE;
-- ddl-end --

-- object: "KLIENT_uq" | type: CONSTRAINT --
-- ALTER TABLE public."KLIENT" DROP CONSTRAINT IF EXISTS "KLIENT_uq" CASCADE;
ALTER TABLE public."KLIENT" ADD CONSTRAINT "KLIENT_uq" UNIQUE ("id_DANE KONTAKTOWE");
-- ddl-end --

-- object: public."CZESC SAMOCHODOWA" | type: TABLE --
-- DROP TABLE IF EXISTS public."CZESC SAMOCHODOWA" CASCADE;
CREATE TABLE public."CZESC SAMOCHODOWA"(
	id integer NOT NULL DEFAULT nextval('CzescSamochodowaSeq'),
	"id_RODZAJ CZESCI SAMOCHODOWEJ" integer,
	info varchar(50) NOT NULL,
	ilosc integer NOT NULL,
	"id_ZAMOWIENIE WEWNETRZNE" integer,
	CONSTRAINT "CZESC_SAMOCHODOWA_ID" PRIMARY KEY (id)

);
-- ddl-end --
ALTER TABLE public."CZESC SAMOCHODOWA" OWNER TO postgres;
-- ddl-end --

-- object: public."RODZAJ CZESCI SAMOCHODOWEJ" | type: TABLE --
-- DROP TABLE IF EXISTS public."RODZAJ CZESCI SAMOCHODOWEJ" CASCADE;
CREATE TABLE public."RODZAJ CZESCI SAMOCHODOWEJ"(
	id integer NOT NULL DEFAULT nextval('RodzajCzesciSamochodowejSeq'),
	rodzaj varchar(32) NOT NULL,
	CONSTRAINT "RODZAJ_CZESCI_SAMOCHODOWEJ_ID" PRIMARY KEY (id)

);
-- ddl-end --
ALTER TABLE public."RODZAJ CZESCI SAMOCHODOWEJ" OWNER TO postgres;
-- ddl-end --

-- object: "RODZAJ CZESCI SAMOCHODOWEJ_fk" | type: CONSTRAINT --
-- ALTER TABLE public."CZESC SAMOCHODOWA" DROP CONSTRAINT IF EXISTS "RODZAJ CZESCI SAMOCHODOWEJ_fk" CASCADE;
ALTER TABLE public."CZESC SAMOCHODOWA" ADD CONSTRAINT "RODZAJ CZESCI SAMOCHODOWEJ_fk" FOREIGN KEY ("id_RODZAJ CZESCI SAMOCHODOWEJ")
REFERENCES public."RODZAJ CZESCI SAMOCHODOWEJ" (id) MATCH FULL
ON DELETE SET NULL ON UPDATE CASCADE;
-- ddl-end --

-- object: public."CZESC EKSPLOATACYJNA" | type: TABLE --
-- DROP TABLE IF EXISTS public."CZESC EKSPLOATACYJNA" CASCADE;
CREATE TABLE public."CZESC EKSPLOATACYJNA"(
	id integer NOT NULL DEFAULT nextval('CzescEksploatacyjnaSeq'),
	"id_RODZAJ CZESCI EKSPLOATACYJNEJ" integer,
	info varchar(50) NOT NULL,
	ilosc integer NOT NULL,
	"id_ZAMOWIENIE WEWNETRZNE" integer,
	CONSTRAINT "CZESC_EKSPLOATACYJNA_ID" PRIMARY KEY (id)

);
-- ddl-end --
ALTER TABLE public."CZESC EKSPLOATACYJNA" OWNER TO postgres;
-- ddl-end --

-- object: public."RODZAJ CZESCI EKSPLOATACYJNEJ" | type: TABLE --
-- DROP TABLE IF EXISTS public."RODZAJ CZESCI EKSPLOATACYJNEJ" CASCADE;
CREATE TABLE public."RODZAJ CZESCI EKSPLOATACYJNEJ"(
	id integer NOT NULL DEFAULT nextval('RodzajCzesciEksploatacyjnejSeq'),
	rodzaj varchar(32) NOT NULL,
	CONSTRAINT "RODZAJ_CZESCI_EKSPLOATACYJNEJ_ID" PRIMARY KEY (id)

);
-- ddl-end --
ALTER TABLE public."RODZAJ CZESCI EKSPLOATACYJNEJ" OWNER TO postgres;
-- ddl-end --

-- object: "RODZAJ CZESCI EKSPLOATACYJNEJ_fk" | type: CONSTRAINT --
-- ALTER TABLE public."CZESC EKSPLOATACYJNA" DROP CONSTRAINT IF EXISTS "RODZAJ CZESCI EKSPLOATACYJNEJ_fk" CASCADE;
ALTER TABLE public."CZESC EKSPLOATACYJNA" ADD CONSTRAINT "RODZAJ CZESCI EKSPLOATACYJNEJ_fk" FOREIGN KEY ("id_RODZAJ CZESCI EKSPLOATACYJNEJ")
REFERENCES public."RODZAJ CZESCI EKSPLOATACYJNEJ" (id) MATCH FULL
ON DELETE SET NULL ON UPDATE CASCADE;
-- ddl-end --

-- object: public."ZAMOWIENIE ZEWNETRZNE" | type: TABLE --
-- DROP TABLE IF EXISTS public."ZAMOWIENIE ZEWNETRZNE" CASCADE;
CREATE TABLE public."ZAMOWIENIE ZEWNETRZNE"(
	id integer NOT NULL DEFAULT nextval('ZamowienieZewnetrzneSeq'),
	"id_SERWIS MAGAZYN" integer NOT NULL,
	CONSTRAINT "ZAMOWIENIE_ZEWNETRZNE_ID" PRIMARY KEY (id)

);
-- ddl-end --
ALTER TABLE public."ZAMOWIENIE ZEWNETRZNE" OWNER TO postgres;
-- ddl-end --

-- object: "SERWIS MAGAZYN_fk" | type: CONSTRAINT --
-- ALTER TABLE public."ZAMOWIENIE ZEWNETRZNE" DROP CONSTRAINT IF EXISTS "SERWIS MAGAZYN_fk" CASCADE;
ALTER TABLE public."ZAMOWIENIE ZEWNETRZNE" ADD CONSTRAINT "SERWIS MAGAZYN_fk" FOREIGN KEY ("id_SERWIS MAGAZYN")
REFERENCES public."SERWIS MAGAZYN" (id) MATCH FULL
ON DELETE RESTRICT ON UPDATE CASCADE;
-- ddl-end --

-- object: public."ZEWNETRZNY DOSTAWCA" | type: TABLE --
-- DROP TABLE IF EXISTS public."ZEWNETRZNY DOSTAWCA" CASCADE;
CREATE TABLE public."ZEWNETRZNY DOSTAWCA"(
	id integer NOT NULL DEFAULT nextval('ZewnetrznyDostawcaSeq'),
	nazwa varchar(30) NOT NULL,
	CONSTRAINT "ZEWNETRZNY_DOSTAWCA_ID" PRIMARY KEY (id)

);
-- ddl-end --
ALTER TABLE public."ZEWNETRZNY DOSTAWCA" OWNER TO postgres;
-- ddl-end --

-- object: public."ZGLOSZENIE" | type: TABLE --
-- DROP TABLE IF EXISTS public."ZGLOSZENIE" CASCADE;
CREATE TABLE public."ZGLOSZENIE"(
	id integer NOT NULL DEFAULT nextval('ZgloszenieSeq'),
	"id_SERWIS" integer NOT NULL,
	priorytet integer NOT NULL,
	CONSTRAINT "ZGLOSZENIE_ID" PRIMARY KEY (id)

);
-- ddl-end --
ALTER TABLE public."ZGLOSZENIE" OWNER TO postgres;
-- ddl-end --

-- object: public."BADANIE OKRESOWE" | type: TABLE --
-- DROP TABLE IF EXISTS public."BADANIE OKRESOWE" CASCADE;
CREATE TABLE public."BADANIE OKRESOWE"(
	id integer NOT NULL DEFAULT nextval('BadaniaOkresoweSeq'),
	"id_ZGLOSZENIE" integer NOT NULL,
	myjnia boolean NOT NULL,
	jazda_probna boolean NOT NULL,
	CONSTRAINT "ZGLOSZENIE_ID_1" PRIMARY KEY (id)

);
-- ddl-end --
ALTER TABLE public."BADANIE OKRESOWE" OWNER TO postgres;
-- ddl-end --

-- object: public."PRZYGOTOWANIE DO SEZONU" | type: TABLE --
-- DROP TABLE IF EXISTS public."PRZYGOTOWANIE DO SEZONU" CASCADE;
CREATE TABLE public."PRZYGOTOWANIE DO SEZONU"(
	id integer NOT NULL DEFAULT nextval('PrzygotowanieDoSezonuSeq'),
	"id_ZGLOSZENIE" integer NOT NULL,
	CONSTRAINT "PRZYGOTOWANIE_DO_SEZONU_ID" PRIMARY KEY (id)

);
-- ddl-end --
ALTER TABLE public."PRZYGOTOWANIE DO SEZONU" OWNER TO postgres;
-- ddl-end --

-- object: public."NAPRAWA" | type: TABLE --
-- DROP TABLE IF EXISTS public."NAPRAWA" CASCADE;
CREATE TABLE public."NAPRAWA"(
	id integer NOT NULL DEFAULT nextval('NaprawaSeq'),
	"id_ZGLOSZENIE" integer NOT NULL,
	myjnia boolean NOT NULL,
	jazda_probna boolean NOT NULL,
	CONSTRAINT "NAPRAWA_ID" PRIMARY KEY (id)

);
-- ddl-end --
ALTER TABLE public."NAPRAWA" OWNER TO postgres;
-- ddl-end --

-- object: "SERWIS_fk" | type: CONSTRAINT --
-- ALTER TABLE public."ZGLOSZENIE" DROP CONSTRAINT IF EXISTS "SERWIS_fk" CASCADE;
ALTER TABLE public."ZGLOSZENIE" ADD CONSTRAINT "SERWIS_fk" FOREIGN KEY ("id_SERWIS")
REFERENCES public."SERWIS" (id) MATCH FULL
ON DELETE RESTRICT ON UPDATE CASCADE;
-- ddl-end --

-- object: "ZGLOSZENIE_fk" | type: CONSTRAINT --
-- ALTER TABLE public."BADANIE OKRESOWE" DROP CONSTRAINT IF EXISTS "ZGLOSZENIE_fk" CASCADE;
ALTER TABLE public."BADANIE OKRESOWE" ADD CONSTRAINT "ZGLOSZENIE_fk" FOREIGN KEY ("id_ZGLOSZENIE")
REFERENCES public."ZGLOSZENIE" (id) MATCH FULL
ON DELETE RESTRICT ON UPDATE CASCADE;
-- ddl-end --

-- object: "BADANIE OKRESOWE_uq" | type: CONSTRAINT --
-- ALTER TABLE public."BADANIE OKRESOWE" DROP CONSTRAINT IF EXISTS "BADANIE OKRESOWE_uq" CASCADE;
ALTER TABLE public."BADANIE OKRESOWE" ADD CONSTRAINT "BADANIE OKRESOWE_uq" UNIQUE ("id_ZGLOSZENIE");
-- ddl-end --

-- object: "ZGLOSZENIE_fk" | type: CONSTRAINT --
-- ALTER TABLE public."NAPRAWA" DROP CONSTRAINT IF EXISTS "ZGLOSZENIE_fk" CASCADE;
ALTER TABLE public."NAPRAWA" ADD CONSTRAINT "ZGLOSZENIE_fk" FOREIGN KEY ("id_ZGLOSZENIE")
REFERENCES public."ZGLOSZENIE" (id) MATCH FULL
ON DELETE RESTRICT ON UPDATE CASCADE;
-- ddl-end --

-- object: "NAPRAWA_uq" | type: CONSTRAINT --
-- ALTER TABLE public."NAPRAWA" DROP CONSTRAINT IF EXISTS "NAPRAWA_uq" CASCADE;
ALTER TABLE public."NAPRAWA" ADD CONSTRAINT "NAPRAWA_uq" UNIQUE ("id_ZGLOSZENIE");
-- ddl-end --

-- object: public."RAPORT" | type: TABLE --
-- DROP TABLE IF EXISTS public."RAPORT" CASCADE;
CREATE TABLE public."RAPORT"(
	id integer NOT NULL DEFAULT nextval('RaportSeq'),
	"id_ZGLOSZENIE" integer NOT NULL,
	"id_PRACOWNIK SZEREGOWY" integer NOT NULL,
	data timestamp NOT NULL,
	CONSTRAINT "RAPORT_ID" PRIMARY KEY (id)

);
-- ddl-end --
ALTER TABLE public."RAPORT" OWNER TO postgres;
-- ddl-end --

-- object: "ZGLOSZENIE_fk" | type: CONSTRAINT --
-- ALTER TABLE public."RAPORT" DROP CONSTRAINT IF EXISTS "ZGLOSZENIE_fk" CASCADE;
ALTER TABLE public."RAPORT" ADD CONSTRAINT "ZGLOSZENIE_fk" FOREIGN KEY ("id_ZGLOSZENIE")
REFERENCES public."ZGLOSZENIE" (id) MATCH FULL
ON DELETE RESTRICT ON UPDATE CASCADE;
-- ddl-end --

-- object: "RAPORT_uq" | type: CONSTRAINT --
-- ALTER TABLE public."RAPORT" DROP CONSTRAINT IF EXISTS "RAPORT_uq" CASCADE;
ALTER TABLE public."RAPORT" ADD CONSTRAINT "RAPORT_uq" UNIQUE ("id_ZGLOSZENIE");
-- ddl-end --

-- object: public."ZGLOSZENIE ZEWNETRZNE" | type: TABLE --
-- DROP TABLE IF EXISTS public."ZGLOSZENIE ZEWNETRZNE" CASCADE;
CREATE TABLE public."ZGLOSZENIE ZEWNETRZNE"(
	id integer NOT NULL DEFAULT nextval('ZgloszenieZewnetrzneSeq'),
	"id_ZGLOSZENIE" integer NOT NULL,
	"id_KLIENT INSTYTUCJONALNY" integer,
	"id_KLIENT INDYWIDUALNY" integer,
	CONSTRAINT "ZLOSZENIE_ZEWNETRZNE_ID" PRIMARY KEY (id)

);
-- ddl-end --
ALTER TABLE public."ZGLOSZENIE ZEWNETRZNE" OWNER TO postgres;
-- ddl-end --

-- object: "ZGLOSZENIE_fk" | type: CONSTRAINT --
-- ALTER TABLE public."ZGLOSZENIE ZEWNETRZNE" DROP CONSTRAINT IF EXISTS "ZGLOSZENIE_fk" CASCADE;
ALTER TABLE public."ZGLOSZENIE ZEWNETRZNE" ADD CONSTRAINT "ZGLOSZENIE_fk" FOREIGN KEY ("id_ZGLOSZENIE")
REFERENCES public."ZGLOSZENIE" (id) MATCH FULL
ON DELETE RESTRICT ON UPDATE CASCADE;
-- ddl-end --

-- object: "ZGLOSZENIE ZEWNETRZNE_uq" | type: CONSTRAINT --
-- ALTER TABLE public."ZGLOSZENIE ZEWNETRZNE" DROP CONSTRAINT IF EXISTS "ZGLOSZENIE ZEWNETRZNE_uq" CASCADE;
ALTER TABLE public."ZGLOSZENIE ZEWNETRZNE" ADD CONSTRAINT "ZGLOSZENIE ZEWNETRZNE_uq" UNIQUE ("id_ZGLOSZENIE");
-- ddl-end --

-- object: "KLIENT INSTYTUCJONALNY_fk" | type: CONSTRAINT --
-- ALTER TABLE public."ZGLOSZENIE ZEWNETRZNE" DROP CONSTRAINT IF EXISTS "KLIENT INSTYTUCJONALNY_fk" CASCADE;
ALTER TABLE public."ZGLOSZENIE ZEWNETRZNE" ADD CONSTRAINT "KLIENT INSTYTUCJONALNY_fk" FOREIGN KEY ("id_KLIENT INSTYTUCJONALNY")
REFERENCES public."KLIENT INSTYTUCJONALNY" (id) MATCH FULL
ON DELETE SET NULL ON UPDATE CASCADE;
-- ddl-end --

-- object: "KLIENT INDYWIDUALNY_fk" | type: CONSTRAINT --
-- ALTER TABLE public."ZGLOSZENIE ZEWNETRZNE" DROP CONSTRAINT IF EXISTS "KLIENT INDYWIDUALNY_fk" CASCADE;
ALTER TABLE public."ZGLOSZENIE ZEWNETRZNE" ADD CONSTRAINT "KLIENT INDYWIDUALNY_fk" FOREIGN KEY ("id_KLIENT INDYWIDUALNY")
REFERENCES public."KLIENT INDYWIDUALNY" (id) MATCH FULL
ON DELETE SET NULL ON UPDATE CASCADE;
-- ddl-end --

-- object: public."ZAMOWIENIE WEWNETRZNE" | type: TABLE --
-- DROP TABLE IF EXISTS public."ZAMOWIENIE WEWNETRZNE" CASCADE;
CREATE TABLE public."ZAMOWIENIE WEWNETRZNE"(
	id integer NOT NULL DEFAULT nextval('ZamowienieWewnetrznySeq'),
	"id_ZGLOSZENIE" integer NOT NULL,
	"id_SERWIS MAGAZYN" integer NOT NULL,
	"id_PRACOWNIK SZEREGOWY" integer NOT NULL,
	CONSTRAINT "ZAMOWIENIE_WEWNETRZNE_ID" PRIMARY KEY (id)

);
-- ddl-end --
ALTER TABLE public."ZAMOWIENIE WEWNETRZNE" OWNER TO postgres;
-- ddl-end --

-- object: "ZGLOSZENIE_fk" | type: CONSTRAINT --
-- ALTER TABLE public."ZAMOWIENIE WEWNETRZNE" DROP CONSTRAINT IF EXISTS "ZGLOSZENIE_fk" CASCADE;
ALTER TABLE public."ZAMOWIENIE WEWNETRZNE" ADD CONSTRAINT "ZGLOSZENIE_fk" FOREIGN KEY ("id_ZGLOSZENIE")
REFERENCES public."ZGLOSZENIE" (id) MATCH FULL
ON DELETE RESTRICT ON UPDATE CASCADE;
-- ddl-end --

-- object: "ZAMOWIENIE WEWNETRZNE_uq" | type: CONSTRAINT --
-- ALTER TABLE public."ZAMOWIENIE WEWNETRZNE" DROP CONSTRAINT IF EXISTS "ZAMOWIENIE WEWNETRZNE_uq" CASCADE;
ALTER TABLE public."ZAMOWIENIE WEWNETRZNE" ADD CONSTRAINT "ZAMOWIENIE WEWNETRZNE_uq" UNIQUE ("id_ZGLOSZENIE");
-- ddl-end --

-- object: "SERWIS MAGAZYN_fk" | type: CONSTRAINT --
-- ALTER TABLE public."ZAMOWIENIE WEWNETRZNE" DROP CONSTRAINT IF EXISTS "SERWIS MAGAZYN_fk" CASCADE;
ALTER TABLE public."ZAMOWIENIE WEWNETRZNE" ADD CONSTRAINT "SERWIS MAGAZYN_fk" FOREIGN KEY ("id_SERWIS MAGAZYN")
REFERENCES public."SERWIS MAGAZYN" (id) MATCH FULL
ON DELETE RESTRICT ON UPDATE CASCADE;
-- ddl-end --

-- object: "PRACOWNIK SZEREGOWY_fk" | type: CONSTRAINT --
-- ALTER TABLE public."ZAMOWIENIE WEWNETRZNE" DROP CONSTRAINT IF EXISTS "PRACOWNIK SZEREGOWY_fk" CASCADE;
ALTER TABLE public."ZAMOWIENIE WEWNETRZNE" ADD CONSTRAINT "PRACOWNIK SZEREGOWY_fk" FOREIGN KEY ("id_PRACOWNIK SZEREGOWY")
REFERENCES public."PRACOWNIK SZEREGOWY" (id) MATCH FULL
ON DELETE RESTRICT ON UPDATE CASCADE;
-- ddl-end --

-- object: public.rodzaj_samochodu | type: TYPE --
-- DROP TYPE IF EXISTS public.rodzaj_samochodu CASCADE;
CREATE TYPE public.rodzaj_samochodu AS
 ENUM ('A','B','C','D','E','F','G','H','I','K');
-- ddl-end --
ALTER TYPE public.rodzaj_samochodu OWNER TO postgres;
-- ddl-end --

-- object: public."SAMOCHOD" | type: TABLE --
-- DROP TABLE IF EXISTS public."SAMOCHOD" CASCADE;
CREATE TABLE public."SAMOCHOD"(
	id integer NOT NULL DEFAULT nextval('SamochodSeq'),
	rodzaj public.rodzaj_samochodu NOT NULL,
	moc integer NOT NULL,
	kolor varchar(20) NOT NULL,
	rocznik integer NOT NULL,
	automatyczna_skrzynia boolean NOT NULL,
	pojemnosc_silnika varchar(5),
	marka varchar(20) NOT NULL,
	model varchar(20) NOT NULL,
	data_przegladu timestamp NOT NULL,
	"id_WYPOZYCZALNIA" integer NOT NULL,
	cena_za_dzien integer NOT NULL,
	czy_wypozyczony boolean NOT NULL,
	wartosc integer NOT NULL,
	CONSTRAINT "SAMOCHOD_PK" PRIMARY KEY (id)

);
-- ddl-end --
ALTER TABLE public."SAMOCHOD" OWNER TO postgres;
-- ddl-end --

-- object: public."SKIEROWANIE NA BADANIE" | type: TABLE --
-- DROP TABLE IF EXISTS public."SKIEROWANIE NA BADANIE" CASCADE;
CREATE TABLE public."SKIEROWANIE NA BADANIE"(
	id integer NOT NULL DEFAULT nextval('SkierowanieNaBadanieSeq'),
	czy_zaakceptowano boolean NOT NULL,
	"id_KIEROWNIK" integer NOT NULL,
	"id_PRACOWNIK SZEREGOWY" integer,
	"id_SERWIS" integer NOT NULL,
	"id_SAMOCHOD" integer NOT NULL,
	CONSTRAINT "SKIEROWANIE_PK" PRIMARY KEY (id)

);
-- ddl-end --
ALTER TABLE public."SKIEROWANIE NA BADANIE" OWNER TO postgres;
-- ddl-end --

-- object: "KIEROWNIK_fk" | type: CONSTRAINT --
-- ALTER TABLE public."SKIEROWANIE NA BADANIE" DROP CONSTRAINT IF EXISTS "KIEROWNIK_fk" CASCADE;
ALTER TABLE public."SKIEROWANIE NA BADANIE" ADD CONSTRAINT "KIEROWNIK_fk" FOREIGN KEY ("id_KIEROWNIK")
REFERENCES public."KIEROWNIK" (id) MATCH FULL
ON DELETE RESTRICT ON UPDATE CASCADE;
-- ddl-end --

-- object: "PRACOWNIK SZEREGOWY_fk" | type: CONSTRAINT --
-- ALTER TABLE public."SKIEROWANIE NA BADANIE" DROP CONSTRAINT IF EXISTS "PRACOWNIK SZEREGOWY_fk" CASCADE;
ALTER TABLE public."SKIEROWANIE NA BADANIE" ADD CONSTRAINT "PRACOWNIK SZEREGOWY_fk" FOREIGN KEY ("id_PRACOWNIK SZEREGOWY")
REFERENCES public."PRACOWNIK SZEREGOWY" (id) MATCH FULL
ON DELETE SET NULL ON UPDATE CASCADE;
-- ddl-end --

-- object: "SERWIS_fk" | type: CONSTRAINT --
-- ALTER TABLE public."SKIEROWANIE NA BADANIE" DROP CONSTRAINT IF EXISTS "SERWIS_fk" CASCADE;
ALTER TABLE public."SKIEROWANIE NA BADANIE" ADD CONSTRAINT "SERWIS_fk" FOREIGN KEY ("id_SERWIS")
REFERENCES public."SERWIS" (id) MATCH FULL
ON DELETE RESTRICT ON UPDATE CASCADE;
-- ddl-end --

-- object: public."HISTORIA NAPRAWY" | type: TABLE --
-- DROP TABLE IF EXISTS public."HISTORIA NAPRAWY" CASCADE;
CREATE TABLE public."HISTORIA NAPRAWY"(
	id integer NOT NULL DEFAULT nextval('HistoriaNaprawySeq'),
	"id_SAMOCHOD" integer NOT NULL,
	opis varchar(255),
	data timestamp NOT NULL,
	"id_NAPRAWA" integer,
	CONSTRAINT "HISTORIA_NAPRAW_PK" PRIMARY KEY (id)

);
-- ddl-end --
ALTER TABLE public."HISTORIA NAPRAWY" OWNER TO postgres;
-- ddl-end --

-- object: "SAMOCHOD_fk" | type: CONSTRAINT --
-- ALTER TABLE public."HISTORIA NAPRAWY" DROP CONSTRAINT IF EXISTS "SAMOCHOD_fk" CASCADE;
ALTER TABLE public."HISTORIA NAPRAWY" ADD CONSTRAINT "SAMOCHOD_fk" FOREIGN KEY ("id_SAMOCHOD")
REFERENCES public."SAMOCHOD" (id) MATCH FULL
ON DELETE RESTRICT ON UPDATE CASCADE;
-- ddl-end --

-- object: public."WYPOZYCZENIE" | type: TABLE --
-- DROP TABLE IF EXISTS public."WYPOZYCZENIE" CASCADE;
CREATE TABLE public."WYPOZYCZENIE"(
	id integer NOT NULL DEFAULT nextval('WypozyczenieSeq'),
	data_wypozyczenia timestamp NOT NULL,
	data_zwrotu timestamp NOT NULL,
	"id_SAMOCHOD" integer NOT NULL,
	"id_KLIENT INDYWIDUALNY" integer,
	"id_KLIENT INSTYTUCJONALNY" integer,
	CONSTRAINT "WYPOZYCZENIE_PK" PRIMARY KEY (id)
);
-- ddl-end --
ALTER TABLE public."WYPOZYCZENIE" OWNER TO postgres;
-- ddl-end --

-- object: "KLIENT INDYWIDUALNY_fk" | type: CONSTRAINT --
-- ALTER TABLE public."WYPOZYCZENIE" DROP CONSTRAINT IF EXISTS "KLIENT INDYWIDUALNY_fk" CASCADE;
ALTER TABLE public."WYPOZYCZENIE" ADD CONSTRAINT "KLIENT INDYWIDUALNY_fk" FOREIGN KEY ("id_KLIENT INDYWIDUALNY")
REFERENCES public."KLIENT INDYWIDUALNY" (id) MATCH FULL
ON DELETE SET NULL ON UPDATE CASCADE;
-- ddl-end --

-- object: "KLIENT INSTYTUCJONALNY_fk" | type: CONSTRAINT --
-- ALTER TABLE public."WYPOZYCZENIE" DROP CONSTRAINT IF EXISTS "KLIENT INSTYTUCJONALNY_fk" CASCADE;
ALTER TABLE public."WYPOZYCZENIE" ADD CONSTRAINT "KLIENT INSTYTUCJONALNY_fk" FOREIGN KEY ("id_KLIENT INSTYTUCJONALNY")
REFERENCES public."KLIENT INSTYTUCJONALNY" (id) MATCH FULL
ON DELETE SET NULL ON UPDATE CASCADE;
-- ddl-end --

-- object: public."REZERWACJA" | type: TABLE --
-- DROP TABLE IF EXISTS public."REZERWACJA" CASCADE;
CREATE TABLE public."REZERWACJA"(
	id integer NOT NULL DEFAULT nextval('RezerwacjaSeq'),
	czy_internetowo boolean NOT NULL,
	data_wynajmu timestamp NOT NULL,
	"id_WYPOZYCZALNIA" integer NOT NULL,
	rodzaj_samochodu public.rodzaj_samochodu NOT NULL,
	rabat integer,
	"id_KLIENT INDYWIDUALNY" integer,
	"id_KLIENT INSTYTUCJONALNY" integer,
	"id_SAMOCHOD" integer NOT NULL,
	czy_potwierdzono boolean,
	CONSTRAINT "REZERWACJA_PK" PRIMARY KEY (id)

);
-- ddl-end --
ALTER TABLE public."REZERWACJA" OWNER TO postgres;
-- ddl-end --

-- object: "WYPOZYCZALNIA_fk" | type: CONSTRAINT --
-- ALTER TABLE public."REZERWACJA" DROP CONSTRAINT IF EXISTS "WYPOZYCZALNIA_fk" CASCADE;
ALTER TABLE public."REZERWACJA" ADD CONSTRAINT "WYPOZYCZALNIA_fk" FOREIGN KEY ("id_WYPOZYCZALNIA")
REFERENCES public."WYPOZYCZALNIA" (id) MATCH FULL
ON DELETE RESTRICT ON UPDATE CASCADE;
-- ddl-end --

-- object: "KLIENT INDYWIDUALNY_fk" | type: CONSTRAINT --
-- ALTER TABLE public."REZERWACJA" DROP CONSTRAINT IF EXISTS "KLIENT INDYWIDUALNY_fk" CASCADE;
ALTER TABLE public."REZERWACJA" ADD CONSTRAINT "KLIENT INDYWIDUALNY_fk" FOREIGN KEY ("id_KLIENT INDYWIDUALNY")
REFERENCES public."KLIENT INDYWIDUALNY" (id) MATCH FULL
ON DELETE SET NULL ON UPDATE CASCADE;
-- ddl-end --

-- object: "KLIENT INSTYTUCJONALNY_fk" | type: CONSTRAINT --
-- ALTER TABLE public."REZERWACJA" DROP CONSTRAINT IF EXISTS "KLIENT INSTYTUCJONALNY_fk" CASCADE;
ALTER TABLE public."REZERWACJA" ADD CONSTRAINT "KLIENT INSTYTUCJONALNY_fk" FOREIGN KEY ("id_KLIENT INSTYTUCJONALNY")
REFERENCES public."KLIENT INSTYTUCJONALNY" (id) MATCH FULL
ON DELETE SET NULL ON UPDATE CASCADE;
-- ddl-end --

-- object: "SAMOCHOD_fk" | type: CONSTRAINT --
-- ALTER TABLE public."WYPOZYCZENIE" DROP CONSTRAINT IF EXISTS "SAMOCHOD_fk" CASCADE;
ALTER TABLE public."WYPOZYCZENIE" ADD CONSTRAINT "SAMOCHOD_fk" FOREIGN KEY ("id_SAMOCHOD")
REFERENCES public."SAMOCHOD" (id) MATCH FULL
ON DELETE RESTRICT ON UPDATE CASCADE;
-- ddl-end --

-- object: "SAMOCHOD_fk" | type: CONSTRAINT --
-- ALTER TABLE public."REZERWACJA" DROP CONSTRAINT IF EXISTS "SAMOCHOD_fk" CASCADE;
ALTER TABLE public."REZERWACJA" ADD CONSTRAINT "SAMOCHOD_fk" FOREIGN KEY ("id_SAMOCHOD")
REFERENCES public."SAMOCHOD" (id) MATCH FULL
ON DELETE RESTRICT ON UPDATE CASCADE;
-- ddl-end --

-- object: "REZERWACJA_uq1" | type: CONSTRAINT --
-- ALTER TABLE public."REZERWACJA" DROP CONSTRAINT IF EXISTS "REZERWACJA_uq1" CASCADE;
ALTER TABLE public."REZERWACJA" ADD CONSTRAINT "REZERWACJA_uq1" UNIQUE ("id_SAMOCHOD");
-- ddl-end --

-- object: "WYPOZYCZALNIA_fk" | type: CONSTRAINT --
-- ALTER TABLE public."SAMOCHOD" DROP CONSTRAINT IF EXISTS "WYPOZYCZALNIA_fk" CASCADE;
ALTER TABLE public."SAMOCHOD" ADD CONSTRAINT "WYPOZYCZALNIA_fk" FOREIGN KEY ("id_WYPOZYCZALNIA")
REFERENCES public."WYPOZYCZALNIA" (id) MATCH FULL
ON DELETE RESTRICT ON UPDATE CASCADE;
-- ddl-end --

-- object: "PRACOWNIK SZEREGOWY_fk" | type: CONSTRAINT --
-- ALTER TABLE public."RAPORT" DROP CONSTRAINT IF EXISTS "PRACOWNIK SZEREGOWY_fk" CASCADE;
ALTER TABLE public."RAPORT" ADD CONSTRAINT "PRACOWNIK SZEREGOWY_fk" FOREIGN KEY ("id_PRACOWNIK SZEREGOWY")
REFERENCES public."PRACOWNIK SZEREGOWY" (id) MATCH FULL
ON DELETE RESTRICT ON UPDATE CASCADE;
-- ddl-end --

-- object: "ZGLOSZENIE_fk" | type: CONSTRAINT --
-- ALTER TABLE public."PRZYGOTOWANIE DO SEZONU" DROP CONSTRAINT IF EXISTS "ZGLOSZENIE_fk" CASCADE;
ALTER TABLE public."PRZYGOTOWANIE DO SEZONU" ADD CONSTRAINT "ZGLOSZENIE_fk" FOREIGN KEY ("id_ZGLOSZENIE")
REFERENCES public."ZGLOSZENIE" (id) MATCH FULL
ON DELETE RESTRICT ON UPDATE CASCADE;
-- ddl-end --

-- object: "PRZYGOTOWANIE DO SEZONU_uq" | type: CONSTRAINT --
-- ALTER TABLE public."PRZYGOTOWANIE DO SEZONU" DROP CONSTRAINT IF EXISTS "PRZYGOTOWANIE DO SEZONU_uq" CASCADE;
ALTER TABLE public."PRZYGOTOWANIE DO SEZONU" ADD CONSTRAINT "PRZYGOTOWANIE DO SEZONU_uq" UNIQUE ("id_ZGLOSZENIE");
-- ddl-end --

-- object: "PLACOWKA_fk" | type: CONSTRAINT --
-- ALTER TABLE public."WYPOZYCZALNIA" DROP CONSTRAINT IF EXISTS "PLACOWKA_fk" CASCADE;
ALTER TABLE public."WYPOZYCZALNIA" ADD CONSTRAINT "PLACOWKA_fk" FOREIGN KEY ("id_PLACOWKA")
REFERENCES public."PLACOWKA" (id) MATCH FULL
ON DELETE RESTRICT ON UPDATE CASCADE;
-- ddl-end --

-- object: "WYPOZYCZALNIA_uq" | type: CONSTRAINT --
-- ALTER TABLE public."WYPOZYCZALNIA" DROP CONSTRAINT IF EXISTS "WYPOZYCZALNIA_uq" CASCADE;
ALTER TABLE public."WYPOZYCZALNIA" ADD CONSTRAINT "WYPOZYCZALNIA_uq" UNIQUE ("id_PLACOWKA");
-- ddl-end --

-- object: "PRACOWNIK SZEREGOWY_fk" | type: CONSTRAINT --
-- ALTER TABLE public."KLIENT INSTYTUCJONALNY" DROP CONSTRAINT IF EXISTS "PRACOWNIK SZEREGOWY_fk" CASCADE;
ALTER TABLE public."KLIENT INSTYTUCJONALNY" ADD CONSTRAINT "PRACOWNIK SZEREGOWY_fk" FOREIGN KEY ("id_PRACOWNIK SZEREGOWY")
REFERENCES public."PRACOWNIK SZEREGOWY" (id) MATCH FULL
ON DELETE RESTRICT ON UPDATE CASCADE;
-- ddl-end --

-- object: "DANE KONTAKTOWE_fk" | type: CONSTRAINT --
-- ALTER TABLE public."PLACOWKA" DROP CONSTRAINT IF EXISTS "DANE KONTAKTOWE_fk" CASCADE;
ALTER TABLE public."PLACOWKA" ADD CONSTRAINT "DANE KONTAKTOWE_fk" FOREIGN KEY ("id_DANE KONTAKTOWE")
REFERENCES public."DANE KONTAKTOWE" (id) MATCH FULL
ON DELETE RESTRICT ON UPDATE CASCADE;
-- ddl-end --

-- object: "PLACOWKA_uq" | type: CONSTRAINT --
-- ALTER TABLE public."PLACOWKA" DROP CONSTRAINT IF EXISTS "PLACOWKA_uq" CASCADE;
ALTER TABLE public."PLACOWKA" ADD CONSTRAINT "PLACOWKA_uq" UNIQUE ("id_DANE KONTAKTOWE");
-- ddl-end --

-- object: "ZAMOWIENIE WEWNETRZNE_fk" | type: CONSTRAINT --
-- ALTER TABLE public."CZESC SAMOCHODOWA" DROP CONSTRAINT IF EXISTS "ZAMOWIENIE WEWNETRZNE_fk" CASCADE;
ALTER TABLE public."CZESC SAMOCHODOWA" ADD CONSTRAINT "ZAMOWIENIE WEWNETRZNE_fk" FOREIGN KEY ("id_ZAMOWIENIE WEWNETRZNE")
REFERENCES public."ZAMOWIENIE WEWNETRZNE" (id) MATCH FULL
ON DELETE SET NULL ON UPDATE CASCADE;
-- ddl-end --

-- object: "ZAMOWIENIE WEWNETRZNE_fk" | type: CONSTRAINT --
-- ALTER TABLE public."CZESC EKSPLOATACYJNA" DROP CONSTRAINT IF EXISTS "ZAMOWIENIE WEWNETRZNE_fk" CASCADE;
ALTER TABLE public."CZESC EKSPLOATACYJNA" ADD CONSTRAINT "ZAMOWIENIE WEWNETRZNE_fk" FOREIGN KEY ("id_ZAMOWIENIE WEWNETRZNE")
REFERENCES public."ZAMOWIENIE WEWNETRZNE" (id) MATCH FULL
ON DELETE SET NULL ON UPDATE CASCADE;
-- ddl-end --

-- object: "NAPRAWA_fk" | type: CONSTRAINT --
-- ALTER TABLE public."HISTORIA NAPRAWY" DROP CONSTRAINT IF EXISTS "NAPRAWA_fk" CASCADE;
ALTER TABLE public."HISTORIA NAPRAWY" ADD CONSTRAINT "NAPRAWA_fk" FOREIGN KEY ("id_NAPRAWA")
REFERENCES public."NAPRAWA" (id) MATCH FULL
ON DELETE SET NULL ON UPDATE CASCADE;
-- ddl-end --

-- object: "HISTORIA NAPRAWY_uq" | type: CONSTRAINT --
-- ALTER TABLE public."HISTORIA NAPRAWY" DROP CONSTRAINT IF EXISTS "HISTORIA NAPRAWY_uq" CASCADE;
ALTER TABLE public."HISTORIA NAPRAWY" ADD CONSTRAINT "HISTORIA NAPRAWY_uq" UNIQUE ("id_NAPRAWA");
-- ddl-end --

-- object: "SAMOCHOD_fk" | type: CONSTRAINT --
-- ALTER TABLE public."SKIEROWANIE NA BADANIE" DROP CONSTRAINT IF EXISTS "SAMOCHOD_fk" CASCADE;
ALTER TABLE public."SKIEROWANIE NA BADANIE" ADD CONSTRAINT "SAMOCHOD_fk" FOREIGN KEY ("id_SAMOCHOD")
REFERENCES public."SAMOCHOD" (id) MATCH FULL
ON DELETE RESTRICT ON UPDATE CASCADE;
-- ddl-end --

-- object: public."SERWIS_MAGAZYN_CZESC_EKSPLOATACYJNA" | type: TABLE --
-- DROP TABLE IF EXISTS public."SERWIS_MAGAZYN_CZESC_EKSPLOATACYJNA" CASCADE;
CREATE TABLE public."SERWIS_MAGAZYN_CZESC_EKSPLOATACYJNA"(
	"id_SERWIS MAGAZYN" integer,
	"id_CZESC EKSPLOATACYJNA" integer
);
-- ddl-end --
ALTER TABLE public."SERWIS_MAGAZYN_CZESC_EKSPLOATACYJNA" OWNER TO postgres;
-- ddl-end --

-- object: "SERWIS MAGAZYN_fk" | type: CONSTRAINT --
-- ALTER TABLE public."SERWIS_MAGAZYN_CZESC_EKSPLOATACYJNA" DROP CONSTRAINT IF EXISTS "SERWIS MAGAZYN_fk" CASCADE;
ALTER TABLE public."SERWIS_MAGAZYN_CZESC_EKSPLOATACYJNA" ADD CONSTRAINT "SERWIS MAGAZYN_fk" FOREIGN KEY ("id_SERWIS MAGAZYN")
REFERENCES public."SERWIS MAGAZYN" (id) MATCH FULL
ON DELETE SET NULL ON UPDATE CASCADE;
-- ddl-end --

-- object: "CZESC EKSPLOATACYJNA_fk" | type: CONSTRAINT --
-- ALTER TABLE public."SERWIS_MAGAZYN_CZESC_EKSPLOATACYJNA" DROP CONSTRAINT IF EXISTS "CZESC EKSPLOATACYJNA_fk" CASCADE;
ALTER TABLE public."SERWIS_MAGAZYN_CZESC_EKSPLOATACYJNA" ADD CONSTRAINT "CZESC EKSPLOATACYJNA_fk" FOREIGN KEY ("id_CZESC EKSPLOATACYJNA")
REFERENCES public."CZESC EKSPLOATACYJNA" (id) MATCH FULL
ON DELETE SET NULL ON UPDATE CASCADE;
-- ddl-end --

-- object: public."SERWIS_MAGAZYN_CZESC_SAMOCHODOWA" | type: TABLE --
-- DROP TABLE IF EXISTS public."SERWIS_MAGAZYN_CZESC_SAMOCHODOWA" CASCADE;
CREATE TABLE public."SERWIS_MAGAZYN_CZESC_SAMOCHODOWA"(
	"id_SERWIS MAGAZYN" integer,
	"id_CZESC SAMOCHODOWA" integer
);
-- ddl-end --
ALTER TABLE public."SERWIS_MAGAZYN_CZESC_SAMOCHODOWA" OWNER TO postgres;
-- ddl-end --

-- object: "SERWIS MAGAZYN_fk" | type: CONSTRAINT --
-- ALTER TABLE public."SERWIS_MAGAZYN_CZESC_SAMOCHODOWA" DROP CONSTRAINT IF EXISTS "SERWIS MAGAZYN_fk" CASCADE;
ALTER TABLE public."SERWIS_MAGAZYN_CZESC_SAMOCHODOWA" ADD CONSTRAINT "SERWIS MAGAZYN_fk" FOREIGN KEY ("id_SERWIS MAGAZYN")
REFERENCES public."SERWIS MAGAZYN" (id) MATCH FULL
ON DELETE SET NULL ON UPDATE CASCADE;
-- ddl-end --

-- object: "CZESC SAMOCHODOWA_fk" | type: CONSTRAINT --
-- ALTER TABLE public."SERWIS_MAGAZYN_CZESC_SAMOCHODOWA" DROP CONSTRAINT IF EXISTS "CZESC SAMOCHODOWA_fk" CASCADE;
ALTER TABLE public."SERWIS_MAGAZYN_CZESC_SAMOCHODOWA" ADD CONSTRAINT "CZESC SAMOCHODOWA_fk" FOREIGN KEY ("id_CZESC SAMOCHODOWA")
REFERENCES public."CZESC SAMOCHODOWA" (id) MATCH FULL
ON DELETE SET NULL ON UPDATE CASCADE;
-- ddl-end --

-- object: public."ZAMOWIENIE_ZEWNETRZNE_ZEWNETRZNY_DOSTAWCA" | type: TABLE --
-- DROP TABLE IF EXISTS public."ZAMOWIENIE_ZEWNETRZNE_ZEWNETRZNY_DOSTAWCA" CASCADE;
CREATE TABLE public."ZAMOWIENIE_ZEWNETRZNE_ZEWNETRZNY_DOSTAWCA"(
	"id_ZAMOWIENIE ZEWNETRZNE" integer,
	"id_ZEWNETRZNY DOSTAWCA" integer
);
-- ddl-end --
ALTER TABLE public."ZAMOWIENIE_ZEWNETRZNE_ZEWNETRZNY_DOSTAWCA" OWNER TO postgres;
-- ddl-end --

-- object: "ZAMOWIENIE ZEWNETRZNE_fk" | type: CONSTRAINT --
-- ALTER TABLE public."ZAMOWIENIE_ZEWNETRZNE_ZEWNETRZNY_DOSTAWCA" DROP CONSTRAINT IF EXISTS "ZAMOWIENIE ZEWNETRZNE_fk" CASCADE;
ALTER TABLE public."ZAMOWIENIE_ZEWNETRZNE_ZEWNETRZNY_DOSTAWCA" ADD CONSTRAINT "ZAMOWIENIE ZEWNETRZNE_fk" FOREIGN KEY ("id_ZAMOWIENIE ZEWNETRZNE")
REFERENCES public."ZAMOWIENIE ZEWNETRZNE" (id) MATCH FULL
ON DELETE SET NULL ON UPDATE CASCADE;
-- ddl-end --

-- object: "ZEWNETRZNY DOSTAWCA_fk" | type: CONSTRAINT --
-- ALTER TABLE public."ZAMOWIENIE_ZEWNETRZNE_ZEWNETRZNY_DOSTAWCA" DROP CONSTRAINT IF EXISTS "ZEWNETRZNY DOSTAWCA_fk" CASCADE;
ALTER TABLE public."ZAMOWIENIE_ZEWNETRZNE_ZEWNETRZNY_DOSTAWCA" ADD CONSTRAINT "ZEWNETRZNY DOSTAWCA_fk" FOREIGN KEY ("id_ZEWNETRZNY DOSTAWCA")
REFERENCES public."ZEWNETRZNY DOSTAWCA" (id) MATCH FULL
ON DELETE SET NULL ON UPDATE CASCADE;
-- ddl-end --

-- object: public."ZAMOWIENIE_ZEWNETRZNE_CZESC_EKSPLOATACYJNA" | type: TABLE --
-- DROP TABLE IF EXISTS public."ZAMOWIENIE_ZEWNETRZNE_CZESC_EKSPLOATACYJNA" CASCADE;
CREATE TABLE public."ZAMOWIENIE_ZEWNETRZNE_CZESC_EKSPLOATACYJNA"(
	"id_ZAMOWIENIE ZEWNETRZNE" integer,
	"id_CZESC EKSPLOATACYJNA" integer
);
-- ddl-end --
ALTER TABLE public."ZAMOWIENIE_ZEWNETRZNE_CZESC_EKSPLOATACYJNA" OWNER TO postgres;
-- ddl-end --

-- object: "ZAMOWIENIE ZEWNETRZNE_fk" | type: CONSTRAINT --
-- ALTER TABLE public."ZAMOWIENIE_ZEWNETRZNE_CZESC_EKSPLOATACYJNA" DROP CONSTRAINT IF EXISTS "ZAMOWIENIE ZEWNETRZNE_fk" CASCADE;
ALTER TABLE public."ZAMOWIENIE_ZEWNETRZNE_CZESC_EKSPLOATACYJNA" ADD CONSTRAINT "ZAMOWIENIE ZEWNETRZNE_fk" FOREIGN KEY ("id_ZAMOWIENIE ZEWNETRZNE")
REFERENCES public."ZAMOWIENIE ZEWNETRZNE" (id) MATCH FULL
ON DELETE SET NULL ON UPDATE CASCADE;
-- ddl-end --

-- object: "CZESC EKSPLOATACYJNA_fk" | type: CONSTRAINT --
-- ALTER TABLE public."ZAMOWIENIE_ZEWNETRZNE_CZESC_EKSPLOATACYJNA" DROP CONSTRAINT IF EXISTS "CZESC EKSPLOATACYJNA_fk" CASCADE;
ALTER TABLE public."ZAMOWIENIE_ZEWNETRZNE_CZESC_EKSPLOATACYJNA" ADD CONSTRAINT "CZESC EKSPLOATACYJNA_fk" FOREIGN KEY ("id_CZESC EKSPLOATACYJNA")
REFERENCES public."CZESC EKSPLOATACYJNA" (id) MATCH FULL
ON DELETE SET NULL ON UPDATE CASCADE;
-- ddl-end --

-- object: public."ZAMOWIENIE_ZEWNETRZNE_CZESC_SAMOCHODOWA" | type: TABLE --
-- DROP TABLE IF EXISTS public."ZAMOWIENIE_ZEWNETRZNE_CZESC_SAMOCHODOWA" CASCADE;
CREATE TABLE public."ZAMOWIENIE_ZEWNETRZNE_CZESC_SAMOCHODOWA"(
	"id_ZAMOWIENIE ZEWNETRZNE" integer,
	"id_CZESC SAMOCHODOWA" integer,
	ilosc integer
);
-- ddl-end --
ALTER TABLE public."ZAMOWIENIE_ZEWNETRZNE_CZESC_SAMOCHODOWA" OWNER TO postgres;
-- ddl-end --

-- object: "ZAMOWIENIE ZEWNETRZNE_fk" | type: CONSTRAINT --
-- ALTER TABLE public."ZAMOWIENIE_ZEWNETRZNE_CZESC_SAMOCHODOWA" DROP CONSTRAINT IF EXISTS "ZAMOWIENIE ZEWNETRZNE_fk" CASCADE;
ALTER TABLE public."ZAMOWIENIE_ZEWNETRZNE_CZESC_SAMOCHODOWA" ADD CONSTRAINT "ZAMOWIENIE ZEWNETRZNE_fk" FOREIGN KEY ("id_ZAMOWIENIE ZEWNETRZNE")
REFERENCES public."ZAMOWIENIE ZEWNETRZNE" (id) MATCH FULL
ON DELETE SET NULL ON UPDATE CASCADE;
-- ddl-end --

-- object: "CZESC SAMOCHODOWA_fk" | type: CONSTRAINT --
-- ALTER TABLE public."ZAMOWIENIE_ZEWNETRZNE_CZESC_SAMOCHODOWA" DROP CONSTRAINT IF EXISTS "CZESC SAMOCHODOWA_fk" CASCADE;
ALTER TABLE public."ZAMOWIENIE_ZEWNETRZNE_CZESC_SAMOCHODOWA" ADD CONSTRAINT "CZESC SAMOCHODOWA_fk" FOREIGN KEY ("id_CZESC SAMOCHODOWA")
REFERENCES public."CZESC SAMOCHODOWA" (id) MATCH FULL
ON DELETE SET NULL ON UPDATE CASCADE;
-- ddl-end --

-- TRIGGERS:

--1.

--1.
ALTER TABLE "WYPOZYCZENIE" ADD COLUMN czas_wypozyczenia interval;

CREATE OR REPLACE FUNCTION set_czas_wypozyczenia() 
RETURNS TRIGGER 
AS $$
BEGIN
  NEW.czas_wypozyczenia := NEW.data_zwrotu - NEW.data_wypozyczenia;
  RETURN NEW;
END $$ LANGUAGE plpgsql;


CREATE TRIGGER set_czas_wypozyczenia_wypozyczenie
BEFORE INSERT OR UPDATE ON "WYPOZYCZENIE"
FOR EACH ROW 
  EXECUTE PROCEDURE set_czas_wypozyczenia();
  
ALTER TABLE "KLIENT INDYWIDUALNY" ADD COLUMN czy_wypozyczenie_aktywne boolean;

CREATE OR REPLACE FUNCTION reset_czy_wypozyczenie_aktywne()
RETURNS TRIGGER
AS $$
BEGIN
  NEW.czy_wypozyczenie_aktywne := FALSE;
  RETURN NEW;
END $$ LANGUAGE plpgsql;

CREATE TRIGGER reset_czy_wypozyczenie_aktywne_klient_indywidualny
BEFORE INSERT ON "KLIENT INDYWIDUALNY"
FOR EACH ROW
  EXECUTE PROCEDURE reset_czy_wypozyczenie_aktywne();


CREATE OR REPLACE FUNCTION set_czy_wypozyczenie_aktywne()
RETURNS TRIGGER
AS $$
BEGIN
  UPDATE "KLIENT INDYWIDUALNY" SET czy_wypozyczenie_aktywne = TRUE
  WHERE "id" = NEW."id_KLIENT INDYWIDUALNY";
  RETURN NEW;
END $$ LANGUAGE plpgsql;

CREATE TRIGGER set_czy_wypozyczenie_aktywne_klient_indywidualny
BEFORE INSERT ON "WYPOZYCZENIE"
FOR EACH ROW
  EXECUTE PROCEDURE set_czy_wypozyczenie_aktywne();
  

